// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCprVxqVLRWKxWRPUFMvu-lwNsFBlWKPGk',
    appId: '1:429705242947:web:fed6a38daf4386f0b2e7f6',
    messagingSenderId: '429705242947',
    projectId: 'clicalendar-e88b7',
    authDomain: 'clicalendar-e88b7.firebaseapp.com',
    storageBucket: 'clicalendar-e88b7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2dilioS80AlibB8aoVT_fqig5myZVk9w',
    appId: '1:429705242947:android:b81838ec0b098433b2e7f6',
    messagingSenderId: '429705242947',
    projectId: 'clicalendar-e88b7',
    storageBucket: 'clicalendar-e88b7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgbI88ukVgTgel_YInaNQejYTn3CF9odg',
    appId: '1:429705242947:ios:ada54a29e6b437c6b2e7f6',
    messagingSenderId: '429705242947',
    projectId: 'clicalendar-e88b7',
    storageBucket: 'clicalendar-e88b7.appspot.com',
    iosBundleId: 'com.example.orgaOrbit',
  );
}
