name: Pages Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Check if commit message contains 'publish'
      run: echo ${{ github.event.head_commit.message }} | grep -q 'publish'
      continue-on-error: true

    - name: Clone repository
      uses: actions/checkout@v2

    - name: Copy 'web' directory to 'gh-pages' branch
      run: |
        git checkout -b temp-branch
        git subtree split --prefix web -b temp-web
        git checkout gh-pages
        git merge --ff-only temp-web
        git branch -D temp-branch
        git branch -D temp-web
        git push origin gh-pages

    - name: Clean up
      run: |
        git checkout main
        git branch -D gh-pages


        